//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication13.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class pie
    {
        public int Id { get; set; }
        [Required]
        public string name { get; set; }
        public string details { get; set; }
        public string prce { get; set; }
        //[Required]
        //[RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg|.gif)$", ErrorMessage = "Only Image files allowed.")]
        public string imageurl { get; set; }
        public int catid { get; set; }
        [NotMapped]
        //[Required]
        //[ValidateFile(ErrorMessage = "Please select a PNG image smaller than 1MB")]
        //[RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg|.gif)$", ErrorMessage = "Only Image files allowed.")]
        public HttpPostedFileBase upload { get; set; }
        public virtual category category { get; set; }
    }
}
